feat: mark form template as archived instead of deleting them right away
cds-snc/platform-forms-client pull request #1179
Opened 2022-10-26 15:57 UTC by craigzour

# Summary | Résumé

closes https://github.com/cds-snc/platform-forms-client/issues/1166
linked to https://github.com/cds-snc/forms-terraform/pull/271

- Changed the form template delete API function in order to mark them as archived instead of deleting them

# Test instructions | Instructions pour tester la modification

- Delete a form template using the admin UI
- It should disappear from the list of templates in the UI but will stay in the database (`yarn prisma:studio`)

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

2022-10-27 13:57 UTC, Moro-Code requested changes
Great work! Have a minor comment

2022-10-27 13:57 UTC, Moro-Code commented on lib/templates.ts
> +    const dateIn30Days = () => {
If this function is being used once. It might as well just be a variable

2022-10-28 14:44 UTC, Moro-Code requested changes

2022-10-28 14:44 UTC, Moro-Code commented on lib/templates.ts
> +    const dateIn30Days = () => {
I do not think this is so much of a concern. The variable is used almost immediately after within the function. But if you wanted you could do the following 

```js
const date = new Date(Date.now() + 2592000000)
```

2022-10-28 14:59 UTC, Moro-Code approved these changes
Looks good to merge !

2022-10-28 15:15 UTC, craigzour commented
Will wait for @bryan-robitaille to merge `feature/permissions` since it would add more conflits to resolve for him.

2022-10-31 14:19 UTC, Moro-Code approved these changes
approved

2022-10-31 14:22 UTC, merged