Fix/myforms menu update
cds-snc/platform-forms-client pull request #1290
Opened 2022-11-18 15:14 UTC by thiessenp-cds

# Summary | Résumé

Adds more links to the cards menu. Also localizes some card related strings.

Note: the "Save to computer" link points to an end point that may or may not exist in the future, also the wording may change to something more like "Download".

2022-11-18 16:09 UTC, craigzour requested changes

2022-11-18 17:41 UTC, thiessenp-cds commented on components/myforms/Card/Card.tsx
> +                  : `/form-builder/create/${id}`,
I'm trying to remember why I had that down as "create'. If I remember right that was the best route at the time but I agree it doesn't make sense

2022-11-18 18:31 UTC, bryan-robitaille commented on components/myforms/Card/Card.tsx
> +                  : `/form-builder/create/${id}`,
the `/form-builder/edit` route doesn't exist... only `create` exists so far.

2022-11-18 18:56 UTC, craigzour commented on components/myforms/Card/Card.tsx
> +                  : `/form-builder/create/${id}`,
I do not get it. I was pretty sure it was the path I used to edit an existing form when I was working on https://github.com/cds-snc/platform-forms-client/pull/1265 . Can't remember what I was doing exactly but I was able to load a form in the form builder

2022-11-22 17:38 UTC, thiessenp-cds commented on components/myforms/Card/Card.tsx
> +                  : `/form-builder/create/${id}`,
Sure, done. (will update the Edit link when a more complete edit path exists)

2022-11-23 20:26 UTC, timarney commented
> Copy to clipboard currently uses an Alert() to show success. (future work to either update or remove)

FYI - Just created and merge a Dialog component that you could repurpose a bit 

See screenshots here: https://github.com/cds-snc/platform-forms-client/pull/1316#issue-1460358911

https://github.com/cds-snc/platform-forms-client/pull/1316/files#diff-addd4fbf791c7d09fecf1775f0ef6b6177dd2d81c5a080836f9c0ae821d6e8b1

2022-11-23 20:48 UTC, thiessenp-cds commented
> 

Thanks! That would certainly be better than an Alert(). I'll ask Sam about it

2022-11-24 18:53 UTC, thiessenp-cds commented
> > Copy to clipboard currently uses an Alert() to show success. (future work to either update or remove)
> 
> RE: Alert
> 
> I just created and merged a Dialog component that you could repurpose a bit
> 
> See screenshots here: [#1316 (comment)](https://github.com/cds-snc/platform-forms-client/pull/1316#issue-1460358911)
> 
> https://github.com/cds-snc/platform-forms-client/pull/1316/files#diff-addd4fbf791c7d09fecf1775f0ef6b6177dd2d81c5a080836f9c0ae821d6e8b1

We went with an inline text updated but I'm sure that dialog will be re-used in the future :)

2022-11-24 18:56 UTC, thiessenp-cds commented on components/myforms/Card/Card.tsx
> +                  ? `/${i18n.language}/id/${id}/settings`
I updated the links but some link are sort of a work in progress. I'll mark this as resolved for now but please bring it up again if the links still look wrong

2022-11-25 15:11 UTC, craigzour submitted a review, later dismissed
LGTM :)

2022-11-25 16:31 UTC, thiessenp-cds commented
> LGTM :)

I seem to have lost a library in between starting and finishing writing this code :D It umm is back now

2022-11-25 16:37 UTC, craigzour approved these changes

2022-11-25 16:45 UTC, merged