[WIP] Pagination state
cds-snc/platform-forms-client pull request #134
Opened 2021-04-21 19:35 UTC by brdunfield

[WIP] As I need to clean up a few things in the TextPage component and fix all the tests.

This PR attempts to encompass existing pages like the confirmation page (and future pages such as a start page) into the DynamicForm component, so that state and formMetadata can more easily be shared.

To that end, I've created the concept of a form "step" in the code and in the routes. In the future, when we add multi part pagination, we can leverage this step value to load / navigate between different steps of forms.

Pages like the start and end pages can also be considered as "steps" of the form. Next will look for a value after the form ID in the URL to parse the step: `/id/{formid}/{stepvariable} . The DynamicForm component now parses the step value found in the route, and can decide what to render based on what it receives. For now, the only "step" implemented is 'confirmation', viewed at `/id/{formid}/confirmation`. Any value other than 'confirmation' will just be ignored and the basic form page will render as usual.

TextPage.tsx is essentially a slightly generalized copy and paste of the old pages > confirmation.js file, which no longer exists.

2021-04-21 19:37 UTC, brdunfield commented on components/containers/DynamicForm/DynamicForm.tsx
> +  step: string;
I think I actually don't need this

2021-04-22 14:57 UTC, brdunfield commented
![](https://github.trello.services/images/mini-trello-icon.png) [Share state across Form pages](https://trello.com/c/aV0jilCy/631-share-state-across-form-pages)

2021-04-22 15:14 UTC, brdunfield commented
![](https://github.trello.services/images/mini-trello-icon.png) [Confirmation page needs to function like a Form step](https://trello.com/c/7qzSEASD/649-confirmation-page-needs-to-function-like-a-form-step)

2021-04-22 15:19 UTC, bryan-robitaille requested changes
A few little tweaks just to enable the i18n routing for the confirmation page.  It's on my radar to write a test checking for the french submission confirmation path... my bad.

2021-04-22 15:19 UTC, bryan-robitaille commented on lib/dataLayer.tsx
> +            pathname: `/id/${formMetadata.id}/confirmation`,
Thinking you meant to modify this line to `/${language}/id/${formMetadata.id}/confirmation` to render `/en/id/2/confirmation`

2021-04-22 15:19 UTC, bryan-robitaille commented on lib/dataLayer.tsx
> +            pathname: `/id/${formMetadata.id}/confirmation`,
Thinking you meant to modify this line to `/${language}/id/${formMetadata.id}/confirmation` to render `/en/id/2/confirmation`

2021-04-22 15:19 UTC, bryan-robitaille commented on lib/tests/dataLayer.test.js
> +          pathname: "/id/1/confirmation",
In order to support the language rendering this would need to check for `"/en/id/1/confirmation"`.

2021-04-22 15:19 UTC, bryan-robitaille commented on lib/tests/dataLayer.test.js
> +        expect.objectContaining({ pathname: "/id/1/confirmation" })
In order to support the language rendering this would need to check for `"/en/id/1/confirmation"`.

2021-04-22 16:35 UTC, bryan-robitaille approved these changes
😃  👍

2021-04-22 16:40 UTC, merged