Admin fr strings
cds-snc/platform-forms-client pull request #2194
Opened 2023-05-31 16:03 UTC by timarney

# Summary | Résumé

Fixes #1704

Cleans up remaining missing strings and updates admin to have a left nav

- Added left nav 
- Redirects from Welcome page to users by default

<img width="500" alt="Screenshot 2023-05-31 at 11 59 24 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/fb9da2ec-cb2f-4277-a41b-8c2240b29f2d">

Also updated the admin login to bring it inline with the rest of the login pages
<img width="500" alt="Screenshot 2023-05-31 at 12 00 10 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/15bf6180-4d61-4a96-ac15-e9b7fa170808">

# Test instructions | Instructions pour tester la modification
- Login and test CDS admin

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

2023-05-31 16:28 UTC, craigzour reviewed
Reviewed and tested. Will not approve right now as I want to make sure the new approach with the redirect depending on permissions is approved by the rest of the team ;)

2023-05-31 19:10 UTC, timarney commented
Pushed the update to re-add view templates for @srtalbot

2023-06-01 12:26 UTC, craigzour requested changes

2023-06-01 12:41 UTC, timarney commented on components/admin/LeftNav/LeftNavigation.tsx
> +      {ability?.can("update", "Privilege") && (
Pushed an update --- let me know if that'S correct.  Feel free to push a commit.

2023-06-01 12:45 UTC, craigzour approved these changes
LGTM :) Nice improvements!

2023-06-01 13:01 UTC, merged