Fix for "name your form" link
cds-snc/platform-forms-client pull request #2213
Opened 2023-06-05 22:30 UTC by daine

# Summary | Résumé

This PR fixes issue #2115 
- #2115

For any UI changes please include screenshots at different breakpoints. It would also be helpful to include a
before and after comparison for each change i.e.

| Before                                          | After                                        |
| ----------------------------------------------- | -------------------------------------------- |
| ![Screenshot 2023-06-05 at 3 26 23 PM](https://github.com/cds-snc/platform-forms-client/assets/916044/8154af8e-4bc9-42aa-9471-0b703d5d1704)
| 
 |

![Screenshot 2023-06-05 at 3 28 06 PM](https://github.com/cds-snc/platform-forms-client/assets/916044/d9afebc2-2873-41bd-bd82-11779b726ec0)

![Screenshot 2023-06-05 at 3 27 57 PM](https://github.com/cds-snc/platform-forms-client/assets/916044/aad41aa2-01eb-4540-9e98-ab2c0577424b)
# Test instructions | Instructions pour tester la modification

Sequential steps (1., 2., 3., ...) that describe how to test this change. You should include
anything outside the README that will help the developer access your changes and be able to test
them such as any environmental setup steps and/or any time-based elements that this requires.
This will help a developer test things out without too much detective work.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

Are there any related issues or tangent features you consider out of scope for
this issue that could be addressed in the future? If so please create issues and provide
links in this section

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [ ] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [ ] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [ ] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [ ] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [ ] Have you modified the change log and updated any relevant documentation?
- [ ] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [ ] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

2023-06-06 16:03 UTC, craigzour submitted a review, later dismissed
Works well!
I see one unresolved question where you would like the approval of design team. Will approve and let you make sure you talk to them before merging ;)

2023-06-06 16:27 UTC, bryan-robitaille requested changes
I'll try to provide some technical guidance on how we can move away from driving component state through url params after lunch but I noticed 2 things in testing.

1. If the form name is not completed after focus a user can still share the form.
![save with no form name](https://github.com/cds-snc/platform-forms-client/assets/25329319/ee2e874b-fae4-4377-80c0-68cca65ae824)
2. If the form name is not completed and a user shifts focus elsewhere on the page the focus button will not return focus to the form name input a second time.
![share state resets](https://github.com/cds-snc/platform-forms-client/assets/25329319/bdad356a-2c51-49ea-b24c-b50cd0c0060b)

2023-06-06 16:30 UTC, craigzour commented
> I'll try to provide some technical guidance on how we can move away from driving component state through url params after lunch but I noticed 2 things in testing.
> 
> 1. If the form name is not completed after focus a user can still share the form.
>    ![save with no form name](https://user-images.githubusercontent.com/25329319/243763553-ee2e874b-fae4-4377-80c0-68cca65ae824.gif)
> 2. If the form name is not completed and a user shifts focus elsewhere on the page the focus button will not return focus to the form name input a second time.
>    ![share state resets](https://user-images.githubusercontent.com/25329319/243763784-bdad356a-2c51-49ea-b24c-b50cd0c0060b.gif)

I think the reason why you can share even if the form name is empty is because you have put something in the form title. If I remember correctly we needed either one to be able to share a form.

2023-06-06 16:51 UTC, daine commented
@bryan-robitaille Thank you! Some thoughts:
> I'll try to provide some technical guidance on how we can move away from driving component state through url params after lunch but I noticed 2 things in testing.

Thanks! The changes in this PR follows the pattern and implementation of the old code so I can see why it needs to be updated

> > 1. If the form name is not completed after focus a user can still share the form.

> I think the reason why you can share even if the form name is empty is because you have put something in the form title. If I remember correctly we needed either one to be able to share a form. Good catch on the second issue!

I believe @craigzour is correct, I'm working on a separate (but related) issue to address the issues with form names and titles

> 2. If the form name is not completed and a user shifts focus elsewhere on the page the focus button will not return focus to the form name input a second time.

This is the same behaviour with the old one that I've found, so it's not a new bug but rather a leftover from the old behavior. I think it's definitely tied in with potentially just changing the previous implementation altogether!

2023-06-06 16:56 UTC, samsadasivan commented
Hey Daine! I like this - could we just switch the shade to gray-500 (#6b7280) for colour contrast for AA. slate-500 (#64748b) also works but may be too fancy hehe 


<img width="838" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/16671230/c6986340-bcab-4873-ad7b-db7ade4d8686">

2023-06-06 18:02 UTC, timarney commented
> Let's work together to get this into a more 'React' state of mind.

@bryan-robitaille fyi if your thinking about refs it gets a little tricky given where the components get built. For the "most" of the form builder elements now have a refs provider which store the "els" in an array.   The "file name" is part of the header hard to get the ref over to the share modal --- the form builder also does quite a bit of focusing so if I remember correctly it was "stealing focus"  Perhaps you have some tricks for that sort of thing :)

2023-06-06 18:16 UTC, timarney commented
As far as the code goes this fixes the issue as described.

Before approving ... from the design end do we want to allow sharing an empty form that has been given a filename?

Related ....

I can't find an issue for it but the "file name" used to auto-populate when a "file title was filled out".    It does fill it out if you enter a "form title" and than navigate to another page.  Fixing that could help.

2023-06-06 19:07 UTC, samsadasivan commented
It definitely used to auto-populated in FR/EN

2023-06-08 17:12 UTC, craigzour approved these changes
LGTM :) Nice work!

2023-06-08 17:13 UTC, timarney commented on components/form-builder/app/navigation/FileName.tsx
> +          logMessage.debug("Calling focus function on fileNameInput");
Let's remove the debug log here.

2023-06-08 17:20 UTC, craigzour submitted a review, later dismissed

2023-06-08 17:42 UTC, timarney commented on lib/hooks/useRefStore.tsx
> +      logMessage.debug(`getRef :key: ${key}, value: ${value}`);
Probably don't need this anymore?

2023-06-08 17:42 UTC, timarney commented on lib/hooks/useRefStore.tsx
> +      logMessage.debug(`setRef :key: ${key}, ref: ${ref}`);
Probably don't need this anymore?

2023-06-08 17:44 UTC, timarney submitted a review, later dismissed
Approving --- just a couple of debug messages left

2023-06-08 18:54 UTC, thiessenp-cds commented on components/form-builder/app/navigation/FileName.tsx
> +  useImperativeHandle(
Nice!

2023-06-08 18:56 UTC, thiessenp-cds approved these changes
I took a quick look at the accessibility issue with the Share menu. The sub menu will need to add some keyboard navigation etc. 

I can confirm that this issue is an existing issue (develop branch). I think it makes sense to open a new issue about this, out of scope etc. I'll approve the work along side other approvals. Nice work! :)

2023-06-09 04:29 UTC, merged