chore: reduce logging noise
cds-snc/platform-forms-client pull request #3845
Opened 2024-06-17 15:17 UTC by wmoussa-gc

Remove the logs that are created each time a user enters an invalid MFA code.

2024-06-17 15:24 UTC, bryan-robitaille requested changes
Just a quick change to ensure there is no confusion with the comment.  Only invalid 2fa codes throw the `CredentialsSignIn` error.

2024-06-17 15:24 UTC, bryan-robitaille commented on lib/auth/nextAuth.ts
> +        // Not a CredentialsSignin error which is for invalid credentials (including 2FA)
```suggestion
        // Not a CredentialsSignin error which is for invalid 2FA credentials

2024-06-17 16:50 UTC, craigzour approved these changes

2024-06-18 11:45 UTC, bryan-robitaille approved these changes

2024-06-18 11:45 UTC, merged