Feature/form templates json validation
cds-snc/platform-forms-client pull request #447
Opened 2021-09-29 16:30 UTC by jeberhardt

# Summary | Résumé

This will validate the JSON that is being uploaded for a form.

# Test instructions | Instructions pour tester la modification

Launch application and upload a form. You can test for a form failing by removing any of the top-level elements: "form", "submission", "internalTitleEn", "internalTitleFr", "publishingStatus". The form will not be uploaded, and an error will appear in the Javascript console in the browser.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

>> The schema will need to be updated to be more accurate, describing the required / optional properties, and the data structure.
>> The error will need to be presented properly to the user in the UI.

2021-10-01 14:18 UTC, Moro-Code requested changes
Code looks fantastic ! Awesome work but we need unit tests on the middleware you created at a minimum

2021-10-01 18:19 UTC, craigzour approved these changes

2021-10-13 15:14 UTC, Moro-Code requested changes
Great work adding tests for the API handler itself. This will certainly help the team to increase test coverage of the code base. You're still missing unit tests for the individual middleware functions. I also left some minor comments

2021-10-13 15:14 UTC, Moro-Code commented on tests/templates.test.js
> +            decoder = new TextDecoder();
If these are going to be on separate lines anyways. Might as well declare them in separate lines. I was a little confused reading this

2021-10-13 15:14 UTC, Moro-Code commented on tests/templates.test.js
> +    expect(res.statusCode).toBe(400);
Something else to check is if you're getting the error messages you expect in the response

2021-10-13 15:14 UTC, Moro-Code commented on tests/templates.test.js
> +describe("Test JSON validation scenarios", () => {
Overall these tests look good ! Well done ! There are some additional test cases like for example the lambda client throwing an error but this is outside the scope of this PR

2021-10-13 15:14 UTC, Moro-Code commented on lib/jsonValidator/jsonValidator.ts
> +const validate = (
I still need unit tests for this. You wrote unit tests for the template handler but this doesn't provide adequate coverage for this file. We need unit tests specifically for the validate middleware

2021-10-13 15:14 UTC, Moro-Code commented on lib/http/allowed.ts
> +const isRequestAllowed = (
I still need unit tests for this. You wrote unit tests for the template handler but this doesn't provide adequate coverage for this file. We need unit tests specifically for the isRequestAllowed middleware

2021-10-13 15:14 UTC, Moro-Code commented on lib/jsonValidator/jsonValidator.ts
> +export type validateOptions = {
This should be capitalized if its a type

2021-10-18 17:50 UTC, falila approved these changes
Great work @jeberhardt. 
A small detail which maybe out of the scope of this PR. See pic. 
IMO , The red circle's content should be removed whenever there is an error otherwise  users might be confused. 
![Screen Shot 2021-10-18 at 1 38 21 PM](https://user-images.githubusercontent.com/3014890/137781555-c228fbdb-c2d0-455c-8b35-950eca83dd28.png)

2021-10-20 14:50 UTC, merged