make footer GC branding configurable
cds-snc/platform-forms-client pull request #847
Opened 2022-06-29 04:37 UTC by falila

# Summary | Résumé
Make Gc branding in the footer configurable via formConfig object. 
closed #804 

# Test instructions | Instructions pour tester la modification

1. create or update an existing form like [TSB Form](https://forms-staging.cdssandbox.xyz/id/25)
2. add the new attribute `disableGCBranding = true`   to `brand`  element like so :  
`    "brand": {
      "disableGcBranding": true or false
    },`
3.  It should remove the GC word from the footer.  

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet
As of today, It is not possible to remove the GC branding in the footer for all forms. 
The implementation works for all forms that have a custom branding enable meaning the `brand` attribute is configured otherwise GC branding will be displayed.  

# Pull Request Checklist

Please complete the following items in the checklist before you request a review:

- [x] Have you completely tested the functionality of change introduced in this PR? Is the PR solving the problem it's meant to solve within the scope of the related issue?
- [x] The PR does not introduce any new issues such as failed tests, console warnings or new bugs.
- [ ] If this PR adds a package have you ensured its licensed correctly and does not add additional security issues?
- [x] Is the code clean, readable and maintainable? Is it easy to understand and comprehend.
- [x] Does your code have adequate comprehensible comments? Do new functions have [docstrings](https://tsdoc.org/)?
- [x] Have you modified the change log and updated any relevant documentation?
- [x] Is there adequate test coverage? Both unit tests and end-to-end tests where applicable?
- [x] If your PR is touching any UI is it accessible? Have you tested it with a screen reader? Have you tested it with automated testing tools such as axe?

2022-07-04 16:58 UTC, jeberhardt commented on components/globals/Footer.js
> +  // remove GC branding if only set to true otherwise always display it.
Would suggest:
```const canRenderGC = !props.formRecord?.formConfig?.form?.brand?.disableGcBranding;```

Then removing the `!` on line 27.

2022-07-04 17:11 UTC, jeberhardt commented
Please take this opportunity to update `templates.schema.json` with details about `brand` and `disableGcBranding`.

2022-07-06 13:37 UTC, jeberhardt approved these changes

2022-07-06 18:14 UTC, bryan-robitaille requested changes
This code does work as intended but I think a quick refactor with the suggestions I provided might make the code more readable and remove unnecessary props being passed to the Footer component.

2022-07-06 18:14 UTC, bryan-robitaille commented on components/globals/Base.js
> +        {!isEmbeddable && <Footer formRecord={formRecord} />}
It's often best practice in React applications to only pass the needed props to a component.  In this case only the `disableGcBranding` is needed for the component to function.
```js
{!isEmbeddable && <Footer disableGcBranding=props.formRecord?.formConfig?.form?.brand?.disableGcBranding}
```

2022-07-06 18:53 UTC, bryan-robitaille submitted a review, later dismissed

2022-07-06 19:39 UTC, bryan-robitaille approved these changes

2022-07-06 20:12 UTC, merged